# Generated by Django 5.0.7 on 2024-12-11 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_rest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(
                default=0,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(regex="^\\+?\\d{9,15}$")
                ],
            ),
            preserve_default=False,
        ),
    ]
