# Generated by Django 5.0.7 on 2024-12-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_rest", "0002_customer_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesperson",
            name="employee_id",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
