# Generated by Django 5.0.7 on 2024-12-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_rest", "0004_alter_customer_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="price",
            field=models.CharField(max_length=200),
        ),
    ]
