# Generated by Django 5.0.7 on 2024-12-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_rest", "0005_alter_sale_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="price",
            field=models.FloatField(),
        ),
    ]
