# Generated by Django 5.0.7 on 2024-12-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_rest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="vip",
            field=models.BooleanField(default=False),
        ),
    ]
