# Generated by Django 5.0.7 on 2025-01-27 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_rest", "0002_appointment_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
